num1 = int(input("Ingrese un número entero:\n"))
num2 = int(input("Ingrese otro numero entero:\n"))
num3 = float(input("Ingrese un número real:\n"))
print()
print(num1 + num2)
print()
print((num1 + num2) * num3)